apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mywebsite
spec:
  source:
    type: Git
    git:
      uri: https://github.com/devopsadvocate007/container-up  # clone this code
    contextDir: httpd-hello-world                    # cd to this directory
    dockerfile: |
      FROM bitnami/apache:latest
      COPY ./public_html/ /app
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: mywebsite:latest